### ISSUE TITLE
typo FunctionsSection -> FunctionSection

### ISSUE THREAD

**Issue by pyfisch** [NikVolf/parity-wasm#22]
The [spec calls it](http://webassembly.org/docs/binary-encoding/#function-section) "function section". I think is also makes more sense and is consistent with the other section names.

**Comment by NikVolf** [comment]
you are right, thanx, we'll update it for 0.6

**Comment by pyfisch** [comment]
I think you forgot to add this when releasing v0.6.

**Comment by NikVolf** [comment]
yep, it's in 0.7, thanx!
