### ISSUE TITLE
Start section serialization lacks section size

### ISSUE THREAD

**Issue by sunfishcode** [NikVolf/parity-wasm#26]
This input:
```
(module
  (type (;0;) (func))
  (func (;0;) (type 0))
  (start 0))
```
converted to wasm via wabt produces this byte sequence (hexdump -C):
```
00000000  00 61 73 6d 01 00 00 00  01 04 01 60 00 00 03 02  |.asm.......`....|
00000010  01 00 08 01 00 0a 04 01  02 00 0b                 |...........|
0000001b
```
and round-tripped with the new roundtrip example program produces this output byte sequence:
```
00000000  00 61 73 6d 01 00 00 00  01 04 01 60 00 00 03 02  |.asm.......`....|
00000010  01 00 08 00 0a 04 01 02  00 0b                    |..........|
0000001a
```
The difference is that the start section is missing the section length. The start section is "08 01 00" in the input and "08 00" in the output.

**Comment by NikVolf** [comment]
yep, there is a bug here:

https://github.com/NikVolf/parity-wasm/blob/master/src/elements/section.rs#L159

i'll add fix in a moment

**Comment by NikVolf** [comment]
That was probably the only section we never used in our wasm mvp
since they are all compiled with `#![no_main]`

thanks for spotting it!
