### ISSUE TITLE
Declare fields of sections as public

### ISSUE THREAD

**Issue by pyfisch** [NikVolf/parity-wasm#28]
Sections are currently defined like this:

```
#[derive(Default)]
pub struct TypeSection(Vec<Type>);
```

To create a new section from scratch one needs use `Default::default()` and then insert the contents using the accessors. It would be a lot easier if the field of the section was declared public.

(I am currently writing a compiler with WebAssembly as the target.)

**Comment by NikVolf** [comment]
oh i think we can add `From<T: IntoIterator<Type>>` implementation for this

**Comment by pyfisch** [comment]
This does work but since I construct a Vec myself it involves copying the
contents.
Is it planned that the sections enforce some variants and not only the
types?

Am 03.06.2017 4:49 nachm. schrieb "Nikolay Volf" <notifications@github.com>:

**Comment by NikVolf** [comment]
yep, on the second thought, i just added `with_*` helper methods for now

see #29

**Comment by pyfisch** [comment]
Perfect. Thanks.
