### ISSUE TITLE
unresolved import 'memoryBase' with  emcc (1.37.16)

### ISSUE THREAD

**Issue by frehberg** [NikVolf/parity-wasm#72]
I am thrilled of your implementation of parity-wasm, very nice :) But I am facing an issue.

I am generating WASM from C++ code using emcc (1.37.16). It seems the compiler is adding an import statement for the global memoryBase (see dis-asm below)

https://frehberg.wordpress.com/2017/07/19/webassembly-from-c/,  

The output of the disassembler looks like:

(module
 (type $0 (func (param i32 i32)))
 (type $1 (func))
 (import "env" "memoryBase" (global $import$0 i32))
 (import "env" "memory" (memory $0 256))
 (import "env" "table" (table 0 anyfunc))
 (import "env" "tableBase" (global $import$3 i32))
...

The label 'memoryBase' is causing parity-wasm to yield error "unresolved import 'memoryBase'" 

Any idea how to get rid of the label memoryBase or any idea how to add it to the environment of the interpreter?

Many thanks in advance.

**Comment by NikVolf** [comment]
Hi, thanks for report!

indeed, i think we forgot to add `memoryBase` to our experimental emscripten runtime, because it's not generated using Rust compiler usually

And there is no way to add globals manually unfortunately 

I will add a fix in a moment!

**Comment by NikVolf** [comment]
Can you try branch from https://github.com/NikVolf/parity-wasm/pull/73 ?

**Comment by frehberg** [comment]
Works like a charme :)

I took one of the sample codes and adapted it for my needs


    let file = & "/dev/myproject/res/simple.wasm";
    let func_name = & "_op_i_i"; // expectes an i32 and returns i32

    let program = parity_wasm::ProgramInstance::with_env_params(
        interpreter::EnvParams {
            total_stack: 128*1024,
            total_memory: 2*1024*1024,
            allow_memory_growth: false,
        }
    ).expect("Program instance to load");

    let module = parity_wasm::deserialize_file(&file).expect("File to be deserialized");

    let args = vec![ RuntimeValue::I32(42) ];

    let execution_params = interpreter::ExecutionParams::from(args);

    let module = program.add_module("main", module, None).expect("Failed to initialize module");

    println!("Result: {:?}", module.execute_export(func_name, execution_params).expect(""));

    println!("succeeded!");
