### ISSUE TITLE
How to resolve pointers in UserFunctionExecutor?

### ISSUE THREAD

**Issue by pchickey** [NikVolf/parity-wasm#82]
First of all, thank you for providing this high quality crate.

I'm experimenting with adding UserFunctions that interpret a function that takes a pointer argument, e.g. a WASM program that calls `extern void puts(const char*, size_t)`.

As far as I can tell, from the `CallerContext<>` argument to `UserFunctionExecutor::execute` there is no way to access the module (and therefore memory) from which the function was called. 

Am I missing something, conceptually? Or is this functionality that can be added?

**Comment by svyatonik** [comment]
Thanks for the question! There's currently no way to access program/module/memory from `CallerContext`. But there is actually a way to access memory from your `UserFunctionExecutor` - we did this in test here:
https://github.com/NikVolf/parity-wasm/blob/master/src/interpreter/tests/basics.rs#L166
you can see how to initialize your `UserFunctionExecutor` here:
https://github.com/NikVolf/parity-wasm/blob/master/src/interpreter/tests/basics.rs#L197
Please let us know if this fits your needs, or not.

**Comment by pchickey** [comment]
Thanks for the quick response! I attempted that, but found that the memory space of that "env" module was different than the module the pointer was into.

Following your example, I need the executor to have access to the memory created by the statement that loads the "main", but also be passed as the parameter into this statement.
https://github.com/NikVolf/parity-wasm/blob/master/src/interpreter/tests/basics.rs#L242

I am still new at Rust but I couldn't convince the borrow checker to let me do that, perhaps there is some escape hatch I am not aware of.

I suspected I may be missing something, conceptually, since there's no way to tell a pointer into one module's memory space from another. I expected that these linear memory regions be "linked" at separate concrete addresses, but this is the first time I'm using wasm and I may not understand the memory model correctly.

**Comment by svyatonik** [comment]
1) wasm **currently** supports single linear memory region only. There are no instructions that are accepting linear memory index - they're all working with memory region with index = 0. So if your module imports memory from `env`, you could just use `env_instance.memory(ItemIndex::Internal(0)).unwrap();` as in ours example
2) if your module **does not** import linear memory from `env` module, then it could declare its own memory region. Then you could post-initialize your executor after instantiating module. I.e.:
2.1) instantiate module (https://github.com/NikVolf/parity-wasm/blob/master/src/interpreter/tests/basics.rs#L242)
2.2) get `module.memory()`
2.3) pass `module.memory()` to your executor
2.4) execute required function

I'll try to prepare an example for 2nd case tomorrow.

**Comment by pchickey** [comment]
Thanks, that clarifies a number of things. I couldn't figure out a way to do step 2.3 without running afoul the borrow checker, so I'll await your example tomorrow - its much appreciated.

**Comment by svyatonik** [comment]
Not sure this deserves separate commit, since it is mostly about Rust, than wasm. So I'm going to leave code here:
```Rust
#[test]
fn native_env_function_own_memory() {
	use parking_lot::Mutex;

	// create program + env module is auto instantiated + env module memory is instantiated (we do not need this)
	let program = ProgramInstance::new().unwrap();

	struct OwnMemoryReference {
		pub memory: Mutex<Option<Arc<MemoryInstance<UserErrorWithCode>>>>,
	}
	struct OwnMemoryExecutor {
		pub memory_ref: Arc<OwnMemoryReference>,
	}

	impl UserFunctionExecutor<UserErrorWithCode> for OwnMemoryExecutor {
		fn execute(&mut self, name: &str, context: CallerContext<UserErrorWithCode>) -> Result<Option<RuntimeValue>, Error<UserErrorWithCode>> {
			match name {
				"add" => {
					let memory = self.memory_ref.memory.lock().as_ref().expect("initialized before execution; qed").clone();
					let memory_value = memory.get(0, 1).unwrap()[0];
					let fn_argument_unused = context.value_stack.pop_as::<u32>().unwrap() as u8;
					let fn_argument = context.value_stack.pop_as::<u32>().unwrap() as u8;
					assert_eq!(fn_argument_unused, 0);

					let sum = memory_value + fn_argument;
					memory.set(0, &vec![sum]).unwrap();
					Ok(Some(RuntimeValue::I32(sum as i32)))
				},
				_ => Err(Error::Trap("not implemented".into()).into()),
			}
		}
	}

	let env_instance = program.module("env").unwrap();
	let memory_ref = Arc::new(OwnMemoryReference { memory: Mutex::new(None) });
	let mut executor = OwnMemoryExecutor { memory_ref: memory_ref.clone() };
	let native_env_instance = Arc::new(env_native_module(env_instance, UserDefinedElements {
		executor: Some(&mut executor),
		globals: HashMap::new(),
		functions: ::std::borrow::Cow::from(SIGNATURES),
	}).unwrap());
	let params = ExecutionParams::with_external("env".into(), native_env_instance);

	// create module definition with its own memory
	// => since we do not import env' memory, all instructions from this module will access this memory
	let module = module()
		.memory().build() // new memory is created
		.with_import(ImportEntry::new("env".into(), "add".into(), External::Function(0))) // import 'native' function
		.function() // add simple wasm function
			.signature().param().i32().param().i32().return_type().i32().build()
			.body().with_opcodes(Opcodes::new(vec![
				Opcode::GetLocal(0),
				Opcode::GetLocal(1),
				Opcode::Call(0),
				Opcode::End,
			])).build()
			.build()
		.build();

	// instantiate module
	let module_instance = program.add_module("main", module, Some(&params.externals)).unwrap();
	// now get memory reference
	let module_memory = module_instance.memory(ItemIndex::Internal(0)).unwrap();
	// post-initialize our executor with memory reference 
	*memory_ref.memory.lock() = Some(module_memory);

	// now execute function => executor updates memory
	assert_eq!(module_instance.execute_index(1, params.clone().add_argument(RuntimeValue::I32(7)).add_argument(RuntimeValue::I32(0))).unwrap().unwrap(),
		RuntimeValue::I32(7));
}
```

**Comment by NikVolf** [comment]
@svyatonik could use a RefCell there instead of Mutex

and i'm sure this scenario deserves at least a test in the codebase

**Comment by svyatonik** [comment]
So be it - I've made a PR #83

**Comment by pchickey** [comment]
Thanks! I was not aware of RefCell, but that solves the problem. I appreciate the help!
